#task_dir: "data/emothaw_tasks/cdt"
#task_dir: "data/emothaw_tasks/cursive_writing"
#task_dir: "data/emothaw_tasks/house"
#task_dir: "data/emothaw_tasks/pentagon"
task_dir: "data/emothaw_tasks/words"


val_ratio: 0.2
batch_size: 16
num_workers: 2
img_size: 224
epochs: 25
freeze_backbone: true
lr: 0.0001
model_name: resnet50    # options: resnet18, resnet50