task_dir: "data/emothaw_tasks/cdt"
#task_dir: "data/emothaw_tasks/cursive_writing"
#task_dir: "data/emothaw_tasks/house"
#task_dir: "data/emothaw_tasks/pentagon"
#task_dir: "data/emothaw_tasks/words"


val_ratio: 0.2
batch_size: 16
num_workers: 2
img_size: 224
epochs: 5
freeze_backbone: false
lr: 0.00001
